# Generated by Django 5.1.6 on 2025-05-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(default='Residential', max_length=100)),
                ('property_face', models.CharField(max_length=50)),
                ('year_built', models.CharField(max_length=10)),
                ('road_type', models.CharField(max_length=50)),
                ('negotiable', models.BooleanField(default=False)),
                ('furnishing', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('price_text', models.CharField(max_length=100)),
                ('purpose', models.CharField(default='Sale', max_length=50)),
                ('property_area', models.CharField(max_length=50)),
                ('built_up_area', models.CharField(max_length=100)),
                ('road_access', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('date_posted', models.DateField()),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.CharField(max_length=10)),
                ('ring_road_distance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=20)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='listings.home')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.home')),
            ],
        ),
    ]
