# Generated by Django 5.1.6 on 2025-05-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_home_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='purpose',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.city'),
        ),
    ]
