# Generated by Django 5.1.6 on 2025-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_city_alter_home_purpose_alter_home_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='toilets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Other', 'Other')], default='Residential', max_length=100),
        ),
    ]
