# Generated by Django 5.1.6 on 2025-05-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_home_bathrooms_home_bedrooms_home_floors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='property_face',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South'), ('North-East', 'North-East'), ('North-West', 'North-West'), ('South-East', 'South-East'), ('South-West', 'South-West')], default='East', max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.propertytype'),
        ),
    ]
