# Generated by Django 5.1.6 on 2025-05-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_propertytype_alter_home_property_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
